// src/projects/projectsData.ts
import type { Project } from './types';

export const projects: Project[] = [
  {
    slug: 'aether-ai',
    name: 'Aether AI',
    status: 'RELEASED',
    releaseState: 'RELEASED',
    releaseType: 'LIVE',
    deployment: {
      provider: 'VERCEL',
      environment: 'PRODUCTION',
      state: 'READY',
      deploymentLabel: 'Recently Updated',
    },
    category: 'Artificial Intelligence',
    liveUrl: 'https://aether-ai-zeta.vercel.app/',
    displayTags: ['AI', 'RAG', 'Local AI', 'Knowledge Management'],
    summary: 'An AI-powered conversational platform focused on intelligent interactions, local AI, RAG, document processing, memory, knowledge management, and AI-assisted conversations.',
    description:
      'Aether AI is a cutting-edge artificial intelligence product designed for intelligent text processing, retrieval-augmented generation (RAG), and contextual assistance. It integrates advanced machine learning models into a modern web application.',
    technologies: [
      'React',
      'Vite',
      'Node.js',
      'Express',
      'MongoDB',
      'MongoDB Atlas',
      'Google Gemini',
      'RAG',
      'Brevo',
      'Vercel',
      'Render',
    ],
    features: [
      'Retrieval-Augmented Generation (RAG)',
      'Intelligent Contextual Assistance',
      'Modern React + Vite Frontend',
      'Cloud Deployment on Vercel & Render',
    ],
  },
  {
    slug: 'gringotts-wizarding-bank',
    name: 'Gringotts Wizarding Bank',
    status: 'RELEASED',
    releaseState: 'RELEASED',
    releaseType: 'LIVE',
    deployment: {
      provider: 'VERCEL',
      environment: 'PRODUCTION',
      state: 'READY',
      deploymentLabel: 'Recently Updated',
    },
    category: 'Banking Simulation',
    liveUrl: 'https://gringotts-wizarding-bank.vercel.app/',
    displayTags: ['Full Stack', 'Banking', 'Web Application'],
    summary: 'A full-stack banking application inspired by the Wizarding World, featuring authentication, vault/account management, deposits, withdrawals, transfers, and transaction history.',
    description:
      'Gringotts Wizarding Bank is a full-stack web application demonstrating secure user authentication, transactional processing, PDF statement generation, and QR code verification. It serves as a portfolio and educational banking simulation.',
    technologies: [
      'React',
      'Vite',
      'React Router DOM',
      'Axios',
      'Framer Motion',
      'React Toastify',
      'Node.js',
      'Express.js',
      'Mongoose',
      'MongoDB',
      'JWT',
      'bcryptjs',
      'Nodemailer',
      'PDFKit',
      'QRCode',
      'Multer',
      'Helmet',
      'Morgan',
      'Cookie Parser',
      'CORS',
      'Express Validator',
    ],
    features: [
      'JWT Authentication & Password Hashing',
      'PDF Statement Generation',
      'QR Code Verification',
      'Full Transaction History Simulation',
    ],
    disclaimer:
      'Gringotts Wizarding Bank is a portfolio project and educational banking simulation. It is not a real bank, financial institution, or payment service.',
  },
  {
    slug: 'voyager-chat',
    name: 'Voyager Chat',
    status: 'In Development',
    releaseState: 'DEVELOPMENT',
    category: 'Communication Application',
    summary: 'A multi-platform real-time messaging application with offline BLE mesh capabilities.',
    description:
      'Voyager Chat is a robust communication platform designed for seamless online messaging and offline peer-to-peer mesh connectivity using Bluetooth Low Energy (BLE). It prioritises privacy with end-to-end encryption across Android, iOS, and Windows.',
    technologies: [
      'Flutter',
      'Node.js',
      'Express.js',
      'PostgreSQL',
      'SQLite',
      'Socket.IO',
      'Bluetooth Low Energy',
      'BLE Mesh',
      'OpenStreetMap',
      'GPS',
      'End-to-End Encryption',
      'Android',
      'iOS',
      'Windows',
    ],
    features: [
      'Real-Time WebSockets via Socket.IO',
      'Offline BLE Mesh Networking',
      'End-to-End Encryption (E2EE)',
      'Location Services with OpenStreetMap & GPS',
    ],
  },
  {
    slug: 'project-blackout',
    name: 'Project Blackout',
    status: 'Upcoming',
    releaseState: 'DEVELOPMENT',
    category: 'Game Development',
    summary: 'A high-performance multiplayer game built on Unreal Engine 5.',
    description:
      'Project Blackout is an upcoming multi-platform action game powered by Unreal Engine 5. It features advanced artificial intelligence, low-latency networking, dynamic vehicle physics, and high-fidelity rendering for Windows and Android (iOS Coming Soon).',
    technologies: [
      'Unreal Engine 5',
      'Windows',
      'Android',
      'iOS (Coming Soon)',
      'DirectX 12',
      'Vulkan',
      'Multiplayer',
      'AI',
      'Networking',
      'Vehicles',
    ],
    features: [
      'Unreal Engine 5 High-Fidelity Graphics',
      'DirectX 12 & Vulkan Graphics APIs',
      'Cross-Platform Deployment (Windows & Android, iOS Coming Soon)',
      'Advanced AI Behaviours & Vehicle Systems',
    ],
  },
];

export const getProjectBySlug = (slug: string): Project | undefined =>
  projects.find((p) => p.slug === slug);

export const getReleasedProjects = (): Project[] =>
  projects.filter((p) => p.status === 'RELEASED' || p.releaseState === 'RELEASED');
